### PR TITLE
FW values.py

### PR DESCRIPTION
**Pull request by Miniz199922**
Fw

### CODE REVIEW

**Comment by Miniz199922** [comment]
Thanks for adding my firmware. Will this directory be updated
going forward?

Andrew Velardi
954.429.3703 | ***@***.***

Anco Precision, Inc.
3191 S.W. 11th Street, Suite 200, Deerfield Beach, FL 33442
Phone 954.429.3703 | Fax 954.429.1340 | www.ancoprecision.com

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail.

**Comment by j-vanetten** [comment]
I haven't been upstreaming changes myself. You should add this fingerprint to the main openpilot repo to ensure it doesn't get lost here for some reason.

**Comment by Miniz199922** [comment]
Yea I did. It's on openpilot master already. Just want to make sure if I
use your fork it would be included in future updates.

Andrew Velardi
954.429.3703 | ***@***.***

Anco Precision, Inc.
3191 S.W. 11th Street, Suite 200, Deerfield Beach, FL 33442
Phone 954.429.3703 | Fax 954.429.1340 | www.ancoprecision.com

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail.

**Comment by Miniz199922** [comment]
Hey whats up. I've been trying experimental mode but keep getting lkas
error. Any advice?
https://connect.comma.ai/5c77528ab6bf019a/1687951235491/1687951641864
Thanks,

Andrew Velardi
954.429.3703 | ***@***.***

*Anco Precision, Inc. will be closed the week of July 3-July 7,2023.*

Anco Precision, Inc.
3191 S.W. 11th Street, Suite 200, Deerfield Beach, FL 33442
Phone 954.429.3703 | Fax 954.429.1340 | www.ancoprecision.com

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail.

**Pull request merged**
